# Usamos una imagen ligera de Node.js
FROM node:20-slim

# Directorio de trabajo dentro del contenedor
WORKDIR /app

# Copiamos los archivos de empaquetado de dependencias
COPY package*.json .

# Instalamos las librerías de Node
RUN npm install

# Copiamos el resto del código del backend
COPY . .

# Exponemos el puerto que use tu backend (suele ser el 5000 o 3000, cámbialo si usas otro)
EXPOSE 5000

# Comando para arrancar tu servidor Node
CMD ["node", "index.js"]